---
sidebar: sidebar 
permalink: get-started/install_acc.html 
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support 
summary: Para instalar o Astra Control Center depois de abordar alguns pré-requisitos ambientais, você fará o download do pacote e a instalação seguindo as etapas descritas. 
---
= Instale o Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Para instalar o Astra Control Center, siga estas etapas:

* <<Instale o Astra Control Center>>
* <<Faça login na IU do Astra Control Center>>




== Instale o Astra Control Center

Para instalar o Centro de Controle Astra, baixe o pacote de instalação no site de suporte da NetApp e execute uma série de comandos para instalar o Operador do Centro de Controle Astra e o Centro de Controle Astra em seu ambiente. Você pode usar este procedimento para instalar o Astra Control Center em ambientes conetados à Internet ou com conexão via rede.

.O que você vai precisar
* link:requirements.html["Antes de começar a instalação, prepare seu ambiente para a implantação do Astra Control Center"].
* A partir do cluster OpenShift, certifique-se de que todos os operadores de cluster estão em um estado saudável (`available`é `true` ):
+
[listing]
----
oc get clusteroperators
----
* A partir do cluster OpenShift, certifique-se de que todos os serviços de API estão em um estado saudável (`available`é `true` ):
+
[listing]
----
oc get apiservices
----


.Sobre esta tarefa
O processo de instalação do Astra Control Center faz o seguinte:

* Instala os componentes do Astra no `netapp-acc` namespace (ou nome personalizado).
* Cria uma conta padrão.
* Estabelece um endereço de e-mail do usuário administrativo padrão e uma senha única padrão para `ACC-<UUID_of_installation>` esta instância do Astra Control Center. Esse usuário é atribuído a função proprietário no sistema e é necessário para fazer login pela primeira vez na IU.
* Ajuda você a determinar que todos os pods do Astra Control Center estão em execução.
* Instala a IU do Astra.



NOTE: Os comandos Podman podem ser usados no lugar dos comandos Docker se você estiver usando o repositório Podman da Red Hat.

.Passos
. Faça o download do pacote Astra Control Center (`astra-control-center-[version].tar.gz`) no https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Site de suporte da NetApp"^].
. Faça o download do zip dos certificados e chaves do Astra Control Center em https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["Site de suporte da NetApp"^].
. (Opcional) Use o seguinte comando para verificar a assinatura do pacote:
+
[listing]
----
openssl dgst -sha256 -verify astra-control-center[version].pub -signature <astra-control-center[version].sig astra-control-center[version].tar.gz
----
. Extraia as imagens:
+
[listing]
----
tar -vxzf astra-control-center-[version].tar.gz
----
. Mude para o diretório Astra.
+
[listing]
----
cd astra-control-center-[version]
----
. Adicione os arquivos no diretório de imagem do Astra Control Center ao seu Registro local.
+

NOTE: Veja um script de exemplo para o carregamento automático de imagens abaixo.

+
.. Faça login no seu Registro do Docker:
+
[listing]
----
docker login [Docker_registry_path]
----
.. Carregue as imagens no Docker.
.. Marque as imagens.
.. Envie as imagens para o seu registo local.


+
[listing]
----
export REGISTRY=[Docker_registry_path]
for astraImageFile in $(ls images/*.tar) ; do
  # Load to local cache. And store the name of the loaded image trimming the 'Loaded images: '
  astraImage=$(docker load --input ${astraImageFile} | sed 's/Loaded image: //')
  astraImage=$(echo ${astraImage} | sed 's!localhost/!!')
  # Tag with local image repo.
  docker tag ${astraImage} ${REGISTRY}/${astraImage}
  # Push to the local repo.
  docker push ${REGISTRY}/${astraImage}
done
----
. (Apenas para Registros com requisitos de autenticação) se você usar um Registro que requer autenticação, você precisa fazer o seguinte:
+
.. Crie o `netapp-acc-operator` namespace:
+
[listing]
----
kubectl create ns netapp-acc-operator
----
+
Resposta:

+
[listing]
----
namespace/netapp-acc-operator created
----
.. Crie um segredo para o `netapp-acc-operator` namespace. Adicione informações do Docker e execute o seguinte comando:
+
[listing]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[Docker_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Resposta da amostra:

+
[listing]
----
secret/astra-registry-cred created
----
.. Crie o `netapp-acc` namespace (ou nome personalizado).
+
[listing]
----
kubectl create ns [netapp-acc or custom]
----
+
Resposta da amostra:

+
[listing]
----
namespace/netapp-acc created
----
.. Crie um segredo para o `netapp-acc` namespace (ou nome personalizado). Adicione informações do Docker e execute o seguinte comando:
+
[listing]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom] --docker-server=[Docker_registry_path] --docker-username=[username] --docker-password=[token]
----
+
Resposta

+
[listing]
----
secret/astra-registry-cred created
----


. Edite a implantação do operador Astra Control Center yaml ) (`astra_control_center_operator_deploy.yaml`para consultar o Registro local e o segredo.
+
[listing]
----
vim astra_control_center_operator_deploy.yaml
----
+
.. Se você usar um Registro que requer autenticação, substitua a linha padrão de `imagePullSecrets: []` pelo seguinte:
+
[listing]
----
imagePullSecrets:
- name: astra-registry-cred
----
.. Altere `[Docker_registry_path]` para a `kube-rbac-prox` imagem para o caminho do registo onde as imagens foram empurradas numa etapa anterior.
.. Altere `[Docker_registry_path]` para a `acc-operator-controller-manager` imagem para o caminho do registo onde as imagens foram empurradas numa etapa anterior.


+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [Docker_registry_path]/kube-rbac-proxy:v0.5.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *image: [Docker_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
      *imagePullSecrets: []*
----
. Edite o arquivo de recurso personalizado (CR) do Astra Control Center (`astra_control_center_min.yaml`):
+
[listing]
----
vim astra_control_center_min.yaml
----
+

NOTE: Se forem necessárias personalizações adicionais para o seu ambiente, pode utilizar `astra_control_center.yaml` como CR alternativo. `astra_control_center_min.yaml` É o CR padrão e é adequado para a maioria das instalações.

+

NOTE: As propriedades configuradas pelo CR não podem ser alteradas após a implantação inicial do Astra Control Center.

+
.. Mude `[Docker_registry_path]` para o caminho do registo onde empurrou as imagens no passo anterior.
.. Altere a `accountName` cadeia de carateres para o nome que deseja associar à conta.
.. Altere a `astraAddress` cadeia de carateres para o FQDN que deseja usar no navegador para acessar o Astra. Não use `http://` ou `https://` no endereço. Copie este FQDN para uso em um <<Faça login na IU do Astra Control Center,passo posterior>>.
.. Altere a `email` cadeia de carateres para o endereço de administrador inicial padrão. Copie este endereço de e-mail para uso em um <<Faça login na IU do Astra Control Center,passo posterior>>.
.. Alterar `enrolled` para AutoSupport para `false` sites sem conetividade com a Internet ou manter `true` para sites conetados.
.. (Opcional) Adicione um nome `firstName` e sobrenome `lastName` do usuário associado à conta. Você pode executar esta etapa agora ou mais tarde dentro da IU.
.. (Opcional) altere o `storageClass` valor para outro recurso de storageClass do Trident, se necessário pela sua instalação.
.. Se você não estiver usando um Registro que requer autorização, exclua a `secret` linha.


+
[listing, subs="+quotes"]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  *accountName: "Example"*
  astraVersion: "ASTRA_VERSION"
  *astraAddress: "astra.example.com"*
  autoSupport:
    *enrolled: true*
  *email: "[admin@example.com]"*
  *firstName: "SRE"*
  *lastName: "Admin"*
  imageRegistry:
    *name: "[Docker_registry_path]"*
    *secret: "astra-registry-cred"*
  *storageClass: "ontap-gold"*
----
. Instale o operador do Centro de Controle Astra:
+
[listing]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
Resposta da amostra:

+
[listing]
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----
. Se você ainda não fez isso em uma etapa anterior, crie o `netapp-acc` namespace (ou personalizado):
+
[listing]
----
kubectl create ns [netapp-acc or custom]
----
+
Resposta da amostra:

+
[listing]
----
namespace/netapp-acc created
----
. Execute o seguinte patch para corrigir link:https://docs.netapp.com/us-en/astra-control-center/release-notes/known-issues.html#Incorrect-ClusterRoleBinding-created-by-Astra-Control-Center-CRD-during-installation["binding de função do cluster"].
. Instale o Astra Control Center no `netapp-acc` namespace (ou personalizado):
+
[listing]
----
kubectl apply -f astra_control_center_min.yaml -n [netapp-acc or custom]
----
+
Resposta da amostra:

+
[listing]
----
astracontrolcenter.astra.netapp.io/astra created
----
. Verifique se todos os componentes do sistema foram instalados com êxito.
+
[listing]
----
kubectl get pods -n [netapp-acc or custom]
----
+
Cada pod deve ter um status de `Running`. Pode levar alguns minutos até que os pods do sistema sejam implantados.

+
Resposta da amostra:

+
[listing]
----
NAME                                         READY   STATUS    RESTARTS   AGE
acc-helm-repo-5fdfff786f-gkv6z               1/1     Running   0          4m58s
activity-649f869bf7-jn5gs                    1/1     Running   0          3m14s
asup-79846b5fdc-s9s97                        1/1     Running   0          3m10s
authentication-84c78f5cf4-qhx9t              1/1     Running   0          118s
billing-9b8496787-v8rzv                      1/1     Running   0          2m54s
bucketservice-5fb876d9d5-wkfvz               1/1     Running   0          3m26s
cloud-extension-f9f4f59c6-dz6s6              1/1     Running   0          3m
cloud-insights-service-5676b8c6d4-6q7lv      1/1     Running   0          2m52s
composite-compute-7dcc9c6d6c-lxdr6           1/1     Running   0          2m50s
composite-volume-74dbfd7577-cd42b            1/1     Running   0          3m2s
credentials-75dbf46f9d-5qm2b                 1/1     Running   0          3m32s
entitlement-6cf875cb48-gkvhp                 1/1     Running   0          3m12s
features-74fd97bb46-vss2n                    1/1     Running   0          3m6s
fluent-bit-ds-2g9jb                          1/1     Running   0          113s
fluent-bit-ds-5tg5h                          1/1     Running   0          113s
fluent-bit-ds-qfxb8                          1/1     Running   0          113s
graphql-server-7769f98b86-p4qrv              1/1     Running   0          90s
identity-566c566cd5-ntfj6                    1/1     Running   0          3m16s
influxdb2-0                                  1/1     Running   0          4m43s
krakend-5cb8d56978-44q66                     1/1     Running   0          93s
license-66cbbc6f48-27kgf                     1/1     Running   0          3m4s
login-ui-584f7fd84b-dmdrp                    1/1     Running   0          87s
loki-0                                       1/1     Running   0          4m44s
metrics-ingestion-service-6dcfddf45f-mhnvh   1/1     Running   0          3m8s
monitoring-operator-78d67b4d4-nxs6v          2/2     Running   0          116s
nats-0                                       1/1     Running   0          4m40s
nats-1                                       1/1     Running   0          4m26s
nats-2                                       1/1     Running   0          4m15s
nautilus-9b664bc55-rn9t8                     1/1     Running   0          2m56s
openapi-dc5ddfb7d-6q8vh                      1/1     Running   0          3m20s
polaris-consul-consul-5tjs7                  1/1     Running   0          4m43s
polaris-consul-consul-5wbnx                  1/1     Running   0          4m43s
polaris-consul-consul-bfvl7                  1/1     Running   0          4m43s
polaris-consul-consul-server-0               1/1     Running   0          4m43s
polaris-consul-consul-server-1               1/1     Running   0          4m43s
polaris-consul-consul-server-2               1/1     Running   0          4m43s
polaris-mongodb-0                            2/2     Running   0          4m49s
polaris-mongodb-1                            2/2     Running   0          4m22s
polaris-mongodb-arbiter-0                    1/1     Running   0          4m49s
polaris-ui-6648875998-75d98                  1/1     Running   0          92s
polaris-vault-0                              1/1     Running   0          4m41s
polaris-vault-1                              1/1     Running   0          4m41s
polaris-vault-2                              1/1     Running   0          4m41s
storage-backend-metrics-69546f4fc8-m7lfj     1/1     Running   0          3m22s
storage-provider-5d46f755b-qfv89             1/1     Running   0          3m30s
support-5dc579865c-z4pwq                     1/1     Running   0          3m18s
telegraf-ds-4452f                            1/1     Running   0          113s
telegraf-ds-gnqxl                            1/1     Running   0          113s
telegraf-ds-jhw74                            1/1     Running   0          113s
telegraf-rs-gg6m4                            1/1     Running   0          113s
telemetry-service-6dcc875f98-zft26           1/1     Running   0          3m24s
tenancy-7f7f77f699-q7l6w                     1/1     Running   0          3m28s
traefik-769d846f9b-c9crt                     1/1     Running   0          83s
traefik-769d846f9b-l9n4k                     1/1     Running   0          67s
trident-svc-8649c8bfc5-pdj79                 1/1     Running   0          2m57s
vault-controller-745879f98b-49c5v            1/1     Running   0          4m51s
----
. (Opcional) para garantir que a instalação esteja concluída, você pode assistir os `acc-operator` logs usando o seguinte comando.
+
[listing]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
. Quando todos os pods estiverem em execução, verifique o sucesso da instalação recuperando a instância do AstraControlCenter instalada pelo Operador do ACC.
+
[listing]
----
kubectl get acc -o yaml -n netapp-acc
----
. Verifique o `status.deploymentState` campo na resposta para o `Deployed` valor. Se a implantação não tiver êxito, uma mensagem de erro será exibida.
+

NOTE: Irá utilizar o `uuid` no passo seguinte.

+
[listing, subs="+quotes"]
----
apiVersion: v1
items:
- apiVersion: astra.netapp.io/v1
  kind: AstraControlCenter
  metadata:
    creationTimestamp: "2021-07-28T21:36:49Z"
    finalizers:
    - astracontrolcenter.netapp.io/finalizer
   generation: 1
    name: astra
    namespace: netapp-acc
    resourceVersion: "27797604"
    selfLink: /apis/astra.netapp.io/v1/namespaces/netapp-acc/astracontrolcenters/astra
    uid: 61cd8b65-047b-431a-ba35-510afcb845f1
  spec:
    accountName: Example
    astraAddress: astra.example.com
    astraResourcesScaler: "Off"
    astraVersion: 21.08.52
    autoSupport:
      enrolled: false
    email: admin@example.com
    firstName: SRE
    lastName: Admin
    imageRegistry:
      name: registry_name/astra
  status:
    certManager: deploy
    *deploymentState: Deployed*
    observedGeneration: 1
    observedVersion: 21.08.52
    postInstall: Complete
    *uuid: c49008a5-4ef1-4c5d-a53e-830daf994116*
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
----
. Para obter a senha única que você usará quando fizer login no Astra Control Center, copie o `status.uuid` valor da resposta na etapa anterior. A palavra-passe é `ACC-` seguida pelo valor UUID (`ACC-[UUID]`ou, neste exemplo, `ACC-c49008a5-4ef1-4c5d-a53e-830daf994116` ).




== Faça login na IU do Astra Control Center

Depois de instalar o ACC, irá alterar a palavra-passe do administrador predefinido e iniciar sessão no painel de controlo da IU do ACC.

.Passos
. Em um navegador, insira o FQDN usado no no `astraAddress`  `astra_control_center_min.yaml`CR quando <<Instale o Astra Control Center,Instalou o ACC>>.
. Aceite os certificados autoassinados quando solicitado.
+

NOTE: Você pode criar um certificado personalizado após o login.

. Na página de login do Astra Control Center, insira o valor usado `email` no `astra_control_center_min.yaml` CR quando <<Instale o Astra Control Center,Instalou o ACC>>, seguido da senha única (`ACC-[UUID]`).
+

NOTE: Se você digitar uma senha incorreta três vezes, a conta de administrador será bloqueada por 15 minutos.

. Selecione *Login*.
. Altere a senha quando solicitado.
+

NOTE: Se este for o seu primeiro login e você esquecer a senha e nenhuma outra conta de usuário administrativo ainda tiver sido criada, entre em Contato com o suporte da NetApp para obter assistência de recuperação de senha.

. (Opcional) Remova o certificado TLS autoassinado existente e substitua-o por um link:../get-started/add-custom-tls-certificate.html["Certificado TLS personalizado assinado por uma autoridade de certificação (CA)"].




== Solucionar problemas da instalação

Se algum dos serviços estiver `Error` no estado, pode inspecionar os registos. Procure códigos de resposta da API na faixa 400 a 500. Eles indicam o lugar onde uma falha aconteceu.

.Passos
. Para inspecionar os logs do operador do Centro de Controle Astra, digite o seguinte:
+
[listing]
----
kubectl logs --follow -n netapp-acc-operator $(kubectl get pods -n netapp-acc-operator -o name)  -c manager
----




== O que vem a seguir

Conclua a implantação executando link:setup_overview.html["tarefas de configuração"]o .
